# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wQN8z_WtoG9gKnCdVWeZJSc43lBnuDrV
"""

print("Below is my Assignment 3", "\nPlease help me better the code ")

print("\033[1m" + "Enter your account details" + "\033[0m")
input("\033[1m" + "First Name :" + "\033[0m")
input("\033[1m" + "Last Name :" + "\033[0m")
input("\033[1m" + "Physical Address :" + "\033[0m")
input("\033[1m" + "City :" + "\033[0m")
input("\033[1m" + "State :" + "\033[0m")
input("\033[1m" + "Zipcode :" + "\033[0m")
price = float(input("House Price:"))
CreditScore = int(input("\033[1m" + "Credit Score:" + "\033[0m"))
print('\n')
if (CreditScore <520 ):
 CreditStatus = "Poor Credit Score"
 DownPayment = price * 1.5
elif (CreditScore >=580 and CreditScore <=619 ):
  CreditStatus = "Poor Credit Score"
  DownPayment = price * 1.2
elif (CreditScore >= 620 and CreditScore <=679):
  CreditStatus = "Below Average"
  DownPayment = price * 0.18
elif (CreditScore >= 680 and CreditScore <=719):
  CreditStatus = "Average"
  DownPayment = price * 0.6
elif (CreditScore >= 720 and CreditScore <=739):
  CreditStatus = "Above Average"
  DownPayment = price * 0.3
elif (CreditScore >= 740 and CreditScore <=779):
  CreditStatus = "Very Good"
  DownPayment = price * 0.1
elif (CreditScore >= 780 and CreditScore <=850):
  CreditStatus = "Excellent"
  DownPayment = "Zero Down Payment"
else:
  print("Invalid Credit Score" + "\nReenter your details.")

print("\033[1m" + "New House Price : " + "\033[0m", price)
print("\033[1m" + "Down Payment :" + "\033[0m", DownPayment )
print("\033[1m" + "Credit Score :" + "\033[0m", CreditScore)
print("\033[1m" + "Credit Status :" + "\033[0m",CreditStatus)

